version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: MySql_Starter
    environment:
      MYSQL_DATABASE: mon_starter
      # So you don't have to use root, but you can if you like
      MYSQL_USER: user
      # You can use whatever password you like
      MYSQL_PASSWORD: password
      # Password for root access
      MYSQL_ROOT_PASSWORD: password
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3400:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - spring-demo
    restart: unless-stopped

  phpmyadmin:
    depends_on:
    - database
    image: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - spring-demo
      
  mail-dev:
    container_name: mail-dev-bsn-starter
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

# Names our volume
volumes:
  my-db:
    driver: local