version: '3.3'
services:
  mail-dev:
    container_name: mail-dev-bsn-ma-cuisine-maison
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge
