version: '3.8'

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ma_cuisine_maison
    ports:
      - "3306:3306"
    networks:
      - ma_cuisine_maison_network

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - ma_cuisine_maison_network

  mail-dev:
    container_name: mail-dev-bsn-ma-cuisine-maison
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - ma_cuisine_maison_network

networks:
  ma_cuisine_maison_network:
